### ISSUE TITLE
allowrecontacting option "For incidental findings" description and The Internationalized Resource Identifier for this term do NOT match

### ISSUE THREAD

**Issue by Fernananas** [fairgenomes/fairgenomes-semantic-model#113]
Description: "Willingness to be contacted when new knowledge regarding incidental findings becomes available to benefit the patient."

iri definition: " A planned process for a subject agrees not to be informed about any incidental finding."

description and definition do not match.

**Comment by joerivandervelde** [comment]
Indeed this is wrong and the other terms in the lookup are not great matches either.
