### ISSUE TITLE
Add ancestry category (maybe replace ethnicity)

### ISSUE THREAD

**Issue by Fernananas** [fairgenomes/fairgenomes-semantic-model#34]
Ethnicity is mostly based on population category defined using ancestry informative markers (AIMs) based on genetic/genomic data. 

When you look in OLS: hancestro, [ancestry category](https://www.ebi.ac.uk/ols/ontologies/hancestro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHANCESTRO_0004&viewMode=All&siblings=false) would be a good replacement for ethnicity.

**Comment by joerivandervelde** [comment]
Excellent suggestion, thanks! done @ https://github.com/joerivandervelde/fairgenomes-semantic-model/commit/8e61efb2424216cf22d936954bfc4564b343d18b
